config/routes.rb
Rails.application.routes.draw do
  default_url_options host: 'relevamientosdigitales.com'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { sessions: 'sessions' },
                               path_names: { sign_in: 'login', sign_out: 'logout' }
  devise_scope :user do
    get '/login' => 'devise/sessions#new', as: 'login'
  end

  root 'visits#index'
  get :help, to: 'home#help'

  resources :visits, only: [:index, :show, :edit, :update] do
    post :assignment, to: 'visits#assign'
    put :remotion, to: 'visits#remove_assignment'
    put :completion, to: 'visits#complete'
    put :in_process
    collection do
      get :assignment, to: 'visits#assignment_index'
      get :automatic_assignment, to: 'visits#automatic_assignment_index'
      post :completed_report, to: 'visits#completed_report'
      get :completed_report, to: 'visits#completed_report_index'
      get :finished_report, to: 'visits#finished_report_index'
      get :report, to: 'visits#report_index'
      post :syncro_visits
      post :auto_assignments
      post :auto_assignments2
    end
  end
  resources :institutions, only: [:show]

  resources :tasks, only: :none do
    put :completion, to: 'tasks#complete'
  end

  resources :users, only: :none, defaults: { format: :json } do
    collection  do
      post 'new_password_request', to: 'users#reset_password'
    end
    put 'new_password', to: 'users#update_password'
  end
  require 'sidekiq/web'
  mount Sidekiq::Web, at: 'sidekiq'
  mount PgHero::Engine, at: 'pghero'
end

app/models/visit.rb
class Visit < ApplicationRecord
  include Filterable

  belongs_to :user
  belongs_to :institution
  has_many :tasks, dependent: :destroy
  has_many :visit_images, dependent: :destroy
  has_many :visit_noises, dependent: :destroy

  validates :status, :priority, :institution, presence: true
  validate :validate_values, :validate_completed_tasks

  enum status: [:pending, :assigned, :in_process, :completed, :sent], _prefix: true

  scope :status, ->(status) { where status: status }
  scope :user_id, ->(user) { where user_id: user }
  scope :assignable, -> { where(status: :pending).or(where(status: :assigned)) }
  scope :assigned_for_tomorrow, lambda {
    where(to_visit_on: Date.tomorrow).assigned_or_in_process
  }
  scope :assigned_or_in_process, -> { where(status: :assigned).or(where(status: :in_process)) }
  scope :completed, -> { where status: :completed }
  scope :finished, -> { where(status: :completed).or(where(status: :sent)) }

  def valid_for_assignment?(user)
    status_pending? && user.assignable?
  end

  def assign_to(user)
    return false unless valid_assignment?(user)
    self.status = 'assigned'
    self.user = user
    self.to_visit_on = Date.tomorrow
    save
  end

  def complete(params)
    ActiveRecord::Base.transaction do
      create_noises(params[:noises])
      create_images(params[:images])
      update_attributes(status: 'completed', completed_at: date_format(params[:completed_at]),
                        observations: params[:observations])
    end
  rescue ActiveRecord::RecordInvalid
    return false
  end

  def assign_to_better_user(users)
    better_user = nil
    users.each do |potential_usr|
      if potential_usr.assignable_for_visit?(self)
        next better_user = potential_usr unless better_user.present?
        better_user = potential_usr if better_user.more_not_finished_visits_than?(potential_usr)
      end
    end
    assign_to(better_user) if better_user.present?
    assigned?
  end

  def status_sent
    update_attributes!(status: 'sent')
  end

  def remove_assignment
    return unless status_assigned?
    self.status = 'pending'
    self.user = nil
    self.to_visit_on = nil
    save
  end

  def finished?
    status_completed?
  end

  def assigned?
    status_assigned?
  end

  def cap_task_related?
    tasks.cap.exists?
  end

  def rgrl_task_related?
    tasks.rgrl.exists?
  end

  def rar_task_related?
    tasks.rar.exists?
  end

  def create_tasks(tasks)
    tasks.each { |task| Task.create!(task_type: task['type'], visit: self) }
  end

  def without_attachments?
    visit_images.count.zero? && visit_noises.count.zero?
  end

  def mark_as_in_process
    return false unless status_assigned?
    update_attributes!(status: :in_process)
    true
  end

  private

  def create_noises(noises)
    return unless noises.present?
    noises.each do |noise|
      VisitNoise.create!(description: noise[:description], decibels: noise[:decibels], visit: self)
    end
  end

  def create_images(images)
    return unless images.present?
    images.each do |image|
      VisitImage.create!(url_image: image[:url_cloud], visit: self)
    end
  end

  def date_format(date)
    Time.zone.parse(date)
  end

  def valid_assignment?(user)
    errors.add(:base, 'El usuario debe ser preventor') unless user.role_preventor?
    errors.add(:base, 'La visita debe estar en estado pendiente') unless status_pending?
    errors.add(:base, 'EL usuario y la visita deben tener la misma zona') unless
        valid_user_zone(user)
    !errors.present?
  end

  def validate_completed_tasks
    errors.add('error', 'La visita contiene tareas sin finalizar') if
      status_completed? && !all_tasks_completed?
  end

  def all_tasks_completed?
    tasks.reject(&:completed?).empty?
  end

  def validate_values
    errors.add('Pending visit', 'Invalid values') unless valid_pending_values?
    errors.add('Completed visit', 'Invalid values') unless valid_completed_values?
    errors.add('Assigned visit', 'Invalid values') unless valid_assigned_values?
  end

  def complete_preventor_data
    return unless role_preventor?
    return if complete_preventor_data?
    errors.add(:latitude, :blank) if latitude.nil?
    errors.add(:longitude, :blank) if longitude.nil?
    errors.add(:zone, :blank) if zone.nil?
  end

  def valid_pending_values?
    status_pending? ? user.blank? && to_visit_on.blank? : user.present? && to_visit_on.present?
  end

  def valid_completed_values?
    status_completed? || status_sent? ? completed_at.present? : completed_at.blank?
  end

  def valid_assigned_values?
    status_assigned? ? valid_assigned_values_fields? : true
  end

  def valid_assigned_values_fields?
    to_visit_on.present? && user.present? && valid_user_zone(user)
  end

  def valid_user_zone(user)
    user.zone.eql?(institution.zone)
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  include HTTParty
  def index
    return render json: { error: 'invalid params' }, status: :bad_request unless
      index_valid_params?
    @visits = Visit.includes(:institution, :user)
                   .filter(params.slice(:status, :user_id))
                   .order(status: :asc, priority: :asc)
    respond_to do |format|
      format.json { render json: @visits, status: :ok }
      format.html
    end
  end

  def assignment_index
    @visits = Visit.includes({ institution: [:zone] }, :user)
                   .assignable.order(status: :asc, priority: :asc, id: :asc)
  end

  def automatic_assignment_index
    @visits = Visit.includes({ institution: [:zone] }, :user)
                   .status_pending.order(priority: :asc, id: :asc)
    @preventors = User.includes(:zone).role_preventor
  end

  def completed_report_index
    completed_visits
  end

  def report_index
    completed_visits
  end

  def finished_report_index
    @visits = Visit.includes(:institution, :user).finished
  end

  def show
    visit.nil? ? show_return_not_found : show_return_ok
  end

  def edit
    unless available_preventor_for_visit?
      return redirect_to assignment_url,
                         alert: 'No existe preventor disponible para asignar a esta visita'
    end
    visit
  end

  def update
    assign
  end

  def assign
    return redirect_to assignment_url, alert: 'Se debe asignar un preventor' unless user.present?
    process_assignment
  end

  def auto_assignments
    visits_by_ids
    users_by_ids
    # TODO: SETEAR URL CORRECTA
    message = 'Se debe seleccionar al menos una visita y un preventor'
    return redirect_to automatic_assignment_visits_url, alert: message if
        invalid_auto_assigment_params
    auto_assignment_process
    auto_assign_response
  end

  def auto_assignments2
    @visits = Visit.where(status: :pending).order(:priority)
    @users = User.where(role: :preventor)
    auto_assignment_process
    auto_assign_response
  end

  def auto_assignment_process
    @assigned_visits = 0
    @pending_visits = 0
    @visits.each do |visit|
      if visit.assign_to_better_user(@users)
        @assigned_visits += 1
      else
        @pending_visits += 1
      end
    end
  end

  def remove_assignment
    return if invalid_remotion?
    if visit.remove_assignment
      redirect_to assignment_visits_url, notice: 'Visita desasignada.'
    else
      redirect_to assignment_visits_url, alert: visit.errors.full_messages.to_sentence
    end
  end

  def complete
    return render json: { error: 'Fecha de finalización requerida' }, status: :bad_request unless
      complete_date_present?
    @msg = 'La visita ya se encuentra finalizada'
    return render json: { error: @msg }, status: :unprocessable_entity if visit.finished?
    complete_response
  end

  def completed_report
    @visits = Visit.completed
    @message = 'No existen nuevas visitas para enviar a la Superintendencia de Riesgo de Trabajo.'
    return redirect_to completed_report_visits_url, alert: @message unless @visits.present?
    ActiveRecord::Base.transaction { @visits.each(&:status_sent) }
    @message = 'Las visitas fueron enviadas a la Superintendencia '\
      'de Riesgo de Trabajo exitosamente.'
    return redirect_to completed_report_visits_url, notice: @message
  rescue ActiveRecord::RecordInvalid => exception
    return redirect_to completed_report_visits_url, alert: exception.message
  end

  def syncro_visits
    response = HTTParty.get('https://private-13dd3-relevamientosart.apiary-mock.com/visits')
    @message = 'No existen nuevas visitas en la Superintendencia de Riesgo de Trabajo.'
    return redirect_to visits_url, alert: @message unless response.present?
    create_visits(response)
  end

  def in_process
    if visit.mark_as_in_process
      head :ok
    else
      render_error('No se puede actualizar la visita', :unprocessable_entity)
    end
  end

  private

  def completed_visits
    @visits = Visit.includes(:institution, :user).completed
  end

  def invalid_auto_assigment_params
    !@visits.present? || !@visits.size.positive? || !@users.present? || !@users.size.positive?
  end

  def visits_by_ids
    @visits = Visit.where(id: params[:visits]).order(:priority) if params[:visits].present?
  end

  def users_by_ids
    @users = User.find(params[:users]) if params[:users].present?
  end

  def create_visits(response_body)
    @visits_created = 0
    @visits_errors = 0
    response_body.each do |visit_json|
      create_visit(visit_json)
    end
    create_visits_response
  end

  def create_visit(visit_json)
    ActiveRecord::Base.transaction do
      visit = Visit.create!(institution_id: visit_json['institution_id'],
                            priority: visit_json['priority'],
                            external_id: visit_json['external_id'])
      visit.create_tasks(visit_json['tasks'])
      @visits_created += 1
    end
  rescue StandardError
    @visits_errors += 1
  end

  def auto_assign_response
    @message = "Se asignaron exitosamente #{@assigned_visits} visitas."
    return redirect_to automatic_assignment_visits_url, notice: @message unless
        @pending_visits.positive?
    @message = "Se asignaron exitosamente #{@assigned_visits} visitas. "\
      "#{@pending_visits} visitas no pudieron ser asignadas."
    return redirect_to automatic_assignment_visits_url, alert: @message if
        @assigned_visits.positive?
    @message = 'No se pudo asignar ninguna visita de forma automática. Intente realizar'\
      ' la asignación de forma manual.'
    redirect_to automatic_assignment_visits_url, alert: @message
  end

  def create_visits_response
    @message = "Se crearon exitosamente #{@visits_created} visitas a realizar."
    return redirect_to visits_url, notice: @message unless @visits_errors.positive?
    @message = "Se crearon exitosamente #{@visits_created} visitas a realizar. "\
      "Existen #{@visits_errors} con inconsistencias."
    return redirect_to visits_url, alert: @message if @visits_created.positive?
    @message = "Todas las visitas (#{@visits_errors}) contienen errores."
    redirect_to visits_url, alert: @message
  end

  def complete_response
    if visit.complete(params)
      render json: visit, status: :ok
    else
      render json: { error: visit.errors.full_messages.to_sentence }, status: :unprocessable_entity
    end
  end

  def visit
    visit_id = params[:id] || params[:visit_id]
    @visit ||= Visit.includes(:institution, :tasks).find(visit_id)
  end

  def user
    user_id = params[:user_id] || params[:visit][:user]
    @user ||= User.find(user_id)
  end

  def show_return_not_found
    respond_to do |format|
      format.json do
        render render_nothing_not_found
      end
      format.html do
        flash[:alert] = 'Visita no encontrada'
        redirect_to visits_url
      end
    end
  end

  def show_return_ok
    respond_to do |format|
      format.json do
        render json: visit, status: :ok
      end
      format.html
    end
  end

  # status and user_id param is optional
  def index_valid_params?
    params[:status].present? ? Visit.statuses.include?(params[:status]) : true
  end

  # completed_at date is mandatory
  def complete_date_present?
    params[:completed_at].present?
  end

  def invalid_remotion?
    return redirect_to visits_url, alert: 'La visita no existe' unless visit.present?
    return redirect_to visits_url, alert: 'La visita no esta en estado: Asignada' unless
        visit.status_assigned?
  end

  def assignment_url
    assignment_visits_url
  end

  def process_assignment
    if visit.assign_to(user)
      redirect_to assignment_url, notice: 'Visita asignada'
    else
      redirect_to assignment_url, alert: visit.errors.full_messages.to_sentence
    end
  end

  def available_preventor_for_visit?
    User.includes(:zone).assignable_for_visit(visit).present?
  end
end

app/views/visits/assignment_index.html.erb
<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3><%= t('activerecord.models.visit.assignments', default: 'Visits') %></h3>
      </div>
    </div>

    <div class="clearfix"></div>
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2><%= t('activerecord.models.visit.other', default: 'Visits') %><small>Asignación manual</small></h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <!--<p>Add class <code>bulk_action</code> to table for bulk actions options on row select</p>-->
          <% if @visits.empty? %>
              <p> No se han encontrado visitas disponibles para esta sección </p>
          <% else %>
            <div class="table-responsive">
              <!--<table class="table table-striped jambo_table">-->
              <table id="datatable" class="table table-striped jambo_table">
                <thead>
                <tr class="headings">
                  <!--<th>-->
                    <!--<input type="checkbox" id="check-all" class="flat">-->
                  <!--</th>-->
                  <th class="column-title">Visita </th>
                  <th class="column-title">Establecimiento </th>
                  <th class="column-title">Zona </th>
                  <th class="column-title">Prioridad </th>
                  <th class="column-title">Estado </th>
                  <th class="column-title">Preventor </th>
                  <th class="column-title">Fecha prevista de inspección </th>
                  <th class="column-title">Fecha de finalización </th>
                  <th class="column-title no-link last"><span class="nobr">Acciones</span>
                  </th>
                  <!--<th class="bulk-actions" colspan="8">-->
                    <!--<a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>-->
                  <!--</th>-->
                </tr>
                </thead>

                <tbody>
                  <% @visits.each do |visit| %>
                      <!-- TODO: intercalar odd pointer / even pointer -->
                      <tr class="odd pointer">
                        <!--<td class="a-center ">-->
                          <!--<input type="checkbox" class="flat" name="table_records">-->
                        <!--</td>-->
                        <td><%= visit.id %></td>
                        <!-- TODO: Agregar navegación a Establecimiento -->
                        <td><%= visit.institution.name %></td>
                        <td><%= visit.institution.zone.name %></td>
                        <td><%= visit.priority %></td>
                        <td><%= Visit.human_attribute_name("status.#{visit.status}") %></td>
                        <!-- TODO: Agregar navegación a Usuario -->
                        <td><%= visit.user.full_name if visit.user.present? %> </td>
                        <td><%= l(visit.to_visit_on, format: :short_date) if visit.to_visit_on.present? %></td>
                        <td><%= l(visit.completed_at, format: :short_date) if visit.finished? %></td>

                        <td class=" last">
                          <% if visit.status_pending? %>
                            <%=  link_to edit_visit_path(id: visit.id), class: "btn btn-primary btn-xs" do %>
                                <i class="fa fa-pencil"></i> Asignar
                            <% end %>
                          <% else %>
                            <%= link_to visit_remotion_path(visit_id: visit.id), method: :put, data: {confirm: "¿Está seguro?"}, class: "btn btn-warning btn-xs" do %>
                                <i class="fa fa-remove"></i> Desasignar
                            <% end %>
                          <% end %>
                        </td>
                        <!--<td class=" last"><a href="#">Ver</a>-->
                      </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /page content -->

app/views/visits/automatic_assignment_index.html.erb
<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3><%= t('activerecord.models.visit.automatic_assignment', default: 'Visits') %></h3>
      </div>
    </div>

    <div class="clearfix"></div>
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2><%= t('activerecord.models.visit.other', default: 'Visits') %><small>Sin preventor asignado</small></h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <!--<p>Add class <code>bulk_action</code> to table for bulk actions options on row select</p>-->
          <% if @visits.empty? %>
              <p> No se han encontrado visitas disponibles para esta sección </p>
          <% else %>
            <div class="table-responsive">
              <table class="table table-striped jambo_table">
                <thead>
                <tr class="headings">
                  <!--<th>-->
                    <!--<input type="checkbox" id="check-all" class="flat">-->
                  <!--</th>-->
                  <th class="column-title">Visita </th>
                  <th class="column-title">Establecimiento </th>
                  <th class="column-title">Zona </th>
                  <th class="column-title">Prioridad </th>
                  <th class="column-title no-link last"><span class="nobr">Estado</span>
                  </th>
                  <!--<th class="bulk-actions" colspan="5">-->
                    <!--<a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>-->
                  <!--</th>-->
                </tr>
                </thead>

                <tbody>
                <% @visits.each do |visit| %>
                    <!-- TODO: intercalar odd pointer / even pointer -->
                    <tr class="odd pointer">
                      <!--<td class="a-center ">-->
                        <!--<input type="checkbox" class="flat" name="table_records">-->
                      <!--</td>-->
                      <td><%= visit.id %></td>
                      <!-- TODO: Agregar navegación a Establecimiento -->
                      <td><%= visit.institution.name %></td>
                      <td><%= visit.institution.zone.name %></td>
                      <td><%= visit.priority %></td>
                      <td class="last"><%= Visit.human_attribute_name("status.#{visit.status}") %></td>
                      <!--<td class=" last"><a href="#">Ver</a>-->
                    </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          <% end %>

          <!--<div class="ln_solid"></div>-->

          <!--<div class="col-md-12 col-sm-12 col-xs-12">-->
            <!--<%#= button_to "Asignar automáticamente", auto_assignments_visits_path, method: :post, class: "btn btn-primary pull-right" %>-->
          <!--</div>-->
        </div>
      </div>

      <div class="x_panel">
        <div class="x_title">
          <h2>Preventores <small>Disponibles para mañana</small></h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <!--<p>Add class <code>bulk_action</code> to table for bulk actions options on row select</p>-->
          <% if @preventors.empty? %>
              <p> No se han encontrado preventores disponibles </p>
          <% else %>
            <div class="table-responsive">
              <table class="table table-striped jambo_table">
                <thead>
                <tr class="headings">
                  <!--<th>-->
                  <!--<input type="checkbox" id="check-all" class="flat">-->
                  <!--</th>-->
                  <th class="column-title">Preventor </th>
                  <th class="column-title">Nombre </th>
                  <th class="column-title">Zona </th>
                  <th class="column-title no-link last"><span class="nobr">Visitas asignadas</span>
                  </th>
                  <!--<th class="bulk-actions" colspan="5">-->
                  <!--<a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>-->
                  <!--</th>-->
                </tr>
                </thead>

                <tbody>
                <% @preventors.each do |preventor| %>
                    <!-- TODO: intercalar odd pointer / even pointer -->
                    <tr class="odd pointer">
                      <!--<td class="a-center ">-->
                      <!--<input type="checkbox" class="flat" name="table_records">-->
                      <!--</td>-->
                      <td><%= preventor.id %></td>
                      <!-- TODO: Agregar navegación a Establecimiento -->
                      <td><%= preventor.full_name %></td>
                      <td><%= preventor.zone.name %></td>
                      <td class="last"><%= preventor.assigned_visits_count_for_tomorrow %></td>
                      <!--<td class=" last"><a href="#">Ver</a>-->
                    </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          <% end %>

          <!--<div class="ln_solid"></div>-->

          <div class="col-md-12 col-sm-12 col-xs-12">
            <% if @visits.empty? || @preventors.empty? %>
              <%= button_to "Asignar automáticamente", auto_assignments2_visits_path, method: :post, class: "btn btn-success pull-right", disabled:"disabled" %>
            <% else %>
                <%= button_to "Asignar automáticamente", auto_assignments2_visits_path, method: :post, class: "btn btn-success pull-right" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /page content -->

app/views/visits/report_index.html.erb
<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3><%= t('activerecord.models.visit.reports', default: 'Visits') %></h3>
      </div>

    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2><%= t('activerecord.models.visit.finished', default: 'Visits') %> </h2>
          </ul>
          <div class="clearfix"></div>
        </div>

        <div class="x_content">
          <% if @visits.empty? %>
              <p> No se han encontrado visitas disponibles para esta sección </p>
          <% else %>
            <div class="table-responsive">
              <table id="datatable-buttons" class="table table-striped jambo_table bulk_action">
                <thead>
                <tr class="headings">
                  <th class="column-title">Visita </th>
                  <th class="column-title">Establecimiento </th>
                  <th class="column-title">Prioridad </th>
                  <th class="column-title">Estado </th>
                  <th class="column-title">Preventor </th>
                  <th class="column-title">Fecha prevista de inspección </th>
                  <th class="column-title">Fecha de finalización </th>
                  <th class="column-title no-link last"><span class="nobr">Acciones</span>
                  <th class="bulk-actions" colspan="7">
                    <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                  </th>
                </tr>
                </thead>

                <tbody>
                <% @visits.each do |visit| %>
                    <tr class="odd pointer">
                      <td><%= visit.id %></td>
                      <td><%= visit.institution.name %></td>
                      <td><%= visit.priority %></td>
                      <td><%= Visit.human_attribute_name("status.#{visit.status}") %></td>
                      <td><%= visit.user.full_name if visit.user.present? %> </td>
                      <td><%= l(visit.to_visit_on, format: :short_date) if visit.to_visit_on.present? %></td>
                      <td><%= l(visit.completed_at, format: :short_date) if visit.finished? %></td>
                      <td>
                        <%=  link_to visit_path(id: visit.id), class: "btn btn-primary btn-xs" do %>
                            <i class="fa fa-file-text"></i> Ver Detalle
                        <% end %>
                      </td>
                <% end %>
                </tbody>
              </table>
            </div>
          <% end %>
        </div>
      </div>
    </div>

      <!-- <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2><%= t('activerecord.models.visit.other', default: 'Visits') %> <small>Solo lectura</small></h2>
        </ul>
        <div class="clearfix"></div>
      </div>

      <div class="x_content">
          <div class="table-responsive">
              <table id="datatable-buttons" class="table table-striped jambo_table bulk_action">
              <thead>
              <tr class="headings">
                <th class="column-title">Visita </th>
                <th class="column-title">Establecimiento </th>
                <th class="column-title">Prioridad </th>
                <th class="column-title">Estado </th>
                <th class="column-title">Preventor </th>
                <th class="column-title">Tareas </th>
                <th class="column-title">Fecha de inspección </th>
                <th class="column-title">Fecha de finalización </th>
                <th class="bulk-actions" colspan="7">
                  <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                </th>
              </tr>
              </thead>

              <tbody>
              <% @visits.each do |visit| %>
                  <tr class="odd pointer">
                    <td><%= visit.id %></td>
                    <td><%= visit.institution.name %></td>
                    <td><%= visit.priority %></td>
                    <td><%= Visit.human_attribute_name("status.#{visit.status}") %></td>
                    <td><%= visit.user.full_name if visit.user.present? %> </td>
                    <td> Descripción de Tareas </td>
                    <td><%= l(visit.to_visit_on, format: :short_date) if visit.to_visit_on.present? %></td>
                    <td><%= l(visit.completed_at, format: :short_date) if visit.finished? %></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
        <div class="ln_solid"></div>
          <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-11">
            <%= button_to "Exportar", completed_report_visits_path, method: :post, class: "btn btn-primary" %>
          </div>
        </div>
      </div> -->
    </div>
  </div>
</div>
<!-- /page content -->