config/routes.rb
Rails.application.routes.draw do
  default_url_options host: 'relevamientosdigitales.com'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { sessions: 'sessions' },
                               path_names: { sign_in: 'login', sign_out: 'logout' }
  devise_scope :user do
    get '/login' => 'devise/sessions#new', as: 'login'
  end

  root 'visits#index'
  get :help, to: 'home#help'

  resources :visits, only: [:index, :show, :edit, :update] do
    post :assignment, to: 'visits#assign'
    put :remotion, to: 'visits#remove_assignment'
    put :completion, to: 'visits#complete'
    put :in_process
    collection do
      get :assignment, to: 'visits#assignment_index'
      get :automatic_assignment, to: 'visits#automatic_assignment_index'
      post :completed_report, to: 'visits#completed_report'
      get :completed_report, to: 'visits#completed_report_index'
      get :finished_report, to: 'visits#finished_report_index'
      get :report, to: 'visits#report_index'
      post :syncro_visits
      post :auto_assignments
      post :auto_assignments2
    end
  end
  resources :institutions, only: [:show]

  resources :tasks, only: :none do
    put :completion, to: 'tasks#complete'
  end

  resources :users, only: :none, defaults: { format: :json } do
    collection  do
      post 'new_password_request', to: 'users#reset_password'
    end
    put 'new_password', to: 'users#update_password'
  end
  require 'sidekiq/web'
  mount Sidekiq::Web, at: 'sidekiq'
  mount PgHero::Engine, at: 'pghero'
end

app/views/shared/_footer.html.erb
<% if user_signed_in? %>
    <!-- footer content -->
    <footer>
      <div class="pull-right">
        Relevamientos Digitales - Proyecto final 2017 para
        <a href="https://www.frba.utn.edu.ar/" class="red">@UTN.BA</a>
      </div>
      <div class="clearfix"></div>
    </footer>
    <!-- /footer content -->
<% end %>

app/views/shared/_navigation.html.erb
<% if user_signed_in? %>
    <div class="col-md-3 left_col">
      <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
          <a href="/" class="site_title"><i class="fa fa-check"></i> <span>Relevamientos ART</span></a>
          <!--<a href="/" class="site_title"><%#= image_tag('favicon-32x32.png', alt: '') %><span>Relevamientos ART</span></a>-->
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
          <div class="profile_pic">
            <%=image_tag("user.png", alt: "...", class: "img-circle profile_img")%>
          </div>
          <div class="profile_info">
            <span>Bienvenido,</span>
            <h2><%= current_user.full_name %></h2>
          </div>
        </div>
        <!-- /menu profile quick info -->

        <br />

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
          <div class="menu_section">
            <h3>Backoffice</h3>
            <ul class="nav side-menu">
              <li><a><i class="fa fa-edit"></i> Visitas <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                  <li><%= link_to 'Seguimiento de Visitas', visits_path %></li>
                  <li><a>Asignación de Visitas<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <!--<li><a href="#">Asignación Manual</a></li>-->
                      <li><%= link_to 'Asignación Manual', assignment_visits_path %></li>
                      <li><%= link_to 'Planificación Automática', automatic_assignment_visits_path %></li>
                    </ul>
                  </li>
                </ul>
              </li>
              <li><a><i class="fa fa-exchange "></i> Interfaz SRT <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                  <li><%= link_to 'Obtener visitas a realizar', syncro_visits_visits_path, method: :post %></li>
                  <li><%= link_to 'Enviar visitas finalizadas', completed_report_visits_path %></li>
                </ul>
              </li>
              <li><a><i class="fa fa-bar-chart-o"></i> Informes <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                  <li><%= link_to 'Impresión de Formularios', report_visits_path %></li>
                  <li><%= link_to 'Informe de cumplimiento de Visitas', finished_report_visits_path %></li>
                </ul>
              </li>
            </ul>
          </div>

          <% if current_user.role_admin? %>
              <div class="menu_section">
                <h3>Admin</h3>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-users"></i> Usuarios <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><%= link_to 'Listado de Usuarios', admin_users_path %></li>
                      <li><%= link_to 'Alta de Usuario', new_admin_user_path %></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-industry"></i> Establecimientos <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><%= link_to 'Listado de Establecimientos', admin_institutions_path %></li>
                      <li><%= link_to 'Alta de Establecimiento', new_admin_institution_path %></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-globe"></i> Zonas <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><%= link_to 'Zonas autorizadas', admin_zones_path %></li>
                      <li><%= link_to 'Alta de Zona autorizada ', new_admin_zone_path %></li>
                    </ul>
                  </li>
                </ul>
              </div>
          <%	end %>

        </div>
        <!-- /sidebar menu -->

        <!-- /menu footer buttons -->
        <!--<div class="sidebar-footer hidden-small">-->
          <!--<a data-toggle="tooltip" data-placement="top" title="Settings">-->
            <!--<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>-->
          <!--</a>-->
          <!--<a data-toggle="tooltip" data-placement="top" title="FullScreen">-->
            <!--<span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>-->
          <!--</a>-->
          <!--<a data-toggle="tooltip" data-placement="top" title="Lock">-->
            <!--<span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>-->
          <!--</a>-->
          <!--<a data-toggle="tooltip" data-placement="top" title="Logout" href="#">-->
            <!--<span class="glyphicon glyphicon-off" aria-hidden="true"></span>-->
          <!--</a>-->
        <!--</div>-->
        <!-- /menu footer buttons -->
      </div>
    </div>

    <!-- top navigation -->
    <div class="top_nav">
      <div class="nav_menu">
        <nav>
          <div class="nav toggle">
            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
          </div>

          <nav class="nav navbar-nav navbar-right">
            <!--<li class="">-->
              <!--<a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">-->
                <!--<%#=image_tag("user.png", alt: "") %><%#=	 current_user.full_name %>-->
                <!--<span class=" fa fa-angle-down"></span>-->
              <!--</a>-->
              <!--<ul class="dropdown-menu dropdown-usermenu pull-right">-->
                <!--&lt;!&ndash;<li>&ndash;&gt;-->
                  <!--&lt;!&ndash;<a href="javascript:;">&ndash;&gt;-->
                    <!--&lt;!&ndash;<i class="fa fa-address-card-o pull-right"></i>&ndash;&gt;-->
                    <!--&lt;!&ndash;<span>Mi Perfil</span>&ndash;&gt;-->
                  <!--&lt;!&ndash;</a>&ndash;&gt;-->
                <!--&lt;!&ndash;</li>&ndash;&gt;-->
                <!--&lt;!&ndash;<li><#%= link_to edit_user_registration_path do %>-->
                      <!--<#%= 'Mi Perfil' %><i class="fa fa-address-card-o pull-right"></i>-->
                  <!--<#% end %>-->
                <!--</li>&ndash;&gt;-->
                <!--&lt;!&ndash;<li>&ndash;&gt;-->
                  <!--&lt;!&ndash;<a href="javascript:;">&ndash;&gt;-->
                    <!--&lt;!&ndash;<i class="fa fa-cog pull-right"></i>&ndash;&gt;-->
                    <!--&lt;!&ndash;<span>Ajustes</span>&ndash;&gt;-->
                  <!--&lt;!&ndash;</a>&ndash;&gt;-->
                <!--&lt;!&ndash;</li>&ndash;&gt;-->
            <!--<li><%#= link_to destroy_user_session_path, method: :delete do %>
                      <%#= 'Salir' %><i class="fa fa-sign-out pull-right"></i>-->
                  <!--<%# end %>-->
                <!--</li>-->
              <!--</ul>-->
            <!--</li>-->
            <li><%= link_to destroy_user_session_path, method: :delete do %>
                  Salir &nbsp;<i class="fa fa-sign-out"></i>
              <% end %>
            </li>
            <li><%= link_to help_path do%>
                 Ayuda &nbsp;<i class="fa fa-question-circle"></i>
              <% end %>
            </li>

            <li role="presentation" class="dropdown">
              <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
              </a></li>

          </ul>
        </nav>
        </nav>
      </div>
    </div>
    <!-- /top navigation -->
<% end %>